sigma957:
  stage: deploy
  image: docker:latest
  services:
   - docker:dind
  tags:
    - docker
  only:
    refs:
      - master
  script:
    - docker build --no-cache --pull .
          --build-arg DOMAIN=https://sigma957.net
          --build-arg SITE=sigma957
          --build-arg CF_ACCOUNT_ID=$CF_ACCOUNT_ID
          --build-arg CF_API_TOKEN=$CF_API_TOKEN
          --build-arg CF_ZONE_ID=$CF_ZONE_SIGMA957_ID
