variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
   - docker:dind
  tags:
    - docker
  only:
    - tags
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --no-cache --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
