languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Graeme Read"
theme = "m10c"
paginate = 8
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Graeme Read"
  description = "Life is not measured by the number of breaths we take, but by the moments that take our breath away."
  menu_item_separator = " - "
  [[params.social]]
    icon = "mail"
    name = "email"
    url = "mailto:graeme@sigma957.net"
  [[params.social]]
    icon = "github"
    name = "github"
    url = "https://github.com/graemer957"
  [[params.social]]
    icon = "gitlab"
    name = "gitlab"
    url = "https://gitlab.com/graemer957"
  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/graemer957"

  [params.style]
   darkestColor = "#242930"
   darkColor = "#353b43"
   lightColor = "#afbac4"
   lightestColor = "#ffffff"
   primaryColor = "#a8d1f6"
